### PR TITLE
several fixes

### LINKED ISSUE #60: Use swf file from remote serwer
Hi, 

When I set:
```
    // ...
    $.popunder.helper.def.fs = 'http://example.com/swf/jq-pu-toolkit.swf';
    $.popunder(window.aThreePopunder, 'body', 'body a');
```
`http://example.com/crossdomain.xml` file:
```
<?xml version="1.0"?>
<!DOCTYPE cross-domain-policy SYSTEM "http://www.adobe.com/xml/dtds/cross-domain-policy.dtd">
<cross-domain-policy>
    <site-control permitted-cross-domain-policies="all"/>
    <allow-access-from domain="*" secure="false"/>
    <allow-http-request-headers-from domain="*" headers="*" secure="false"/>
</cross-domain-policy>
```

I use popunder mechanism in domain: `http://mydomain.com` with above settings. `swf` file is loaded and flash-overlays are created for each `a` elements. 

Problem is when I click `a` element because nothing happend. What is wrong?

### PR DESCRIPTION
**Pull request by SBD580**
- fixes #60 (by adding param of 'allowScriptAccess')
- use 'jQuery' instead of '$' variable in action script (was not compatible with jquery in noConflict mode)
- added haxe as a (dev) dependency
- use haxe from node_modules rather then from global scope
- changed swf destination to 'dist' dir in the xml and remove 'mv' command from Gruntfile (now working on windows as well)
- open background tab from flash. Regular background tab was blocked by chrome.

### CODE REVIEW

**Comment by elzerox** [comment]
Hi, I can't get popunder or tab for chrome with flash layer working

I'm trying with this conf and the index.html doesn't do anything in chrome

// flash-url (e.g. jq-pu-toolkit.swf) I copied the file to the same folder
fs: 'jq-pu-toolkit.swf',

// the background tab to open from the flash (e.g close.html)
fsCloseLink: 'close.html',

// user-agents to skip después de ahí borré el chrome
I tried deleting chrome for user-agents skip too...

**Comment by SBD580** [comment]
flash overlay will only work with trigger selector

**Comment by hpbuniat** [comment]
Thank you very much @SBD580, this is awesome. I was working on the same approach as well and merged your changes with some enhancements, e.g. to handle flash-click-to-play.

**Comment by SBD580** [comment]
no problem. see what you did, good work :)

**Pull request merged**
